name: wastemaster_app
description: WasteMaster Gamified Recycling App

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # API
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # QR Scanner
  mobile_scanner: ^3.5.5
  
  # Fonts & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
